// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmaxupvqpmxuojxdmwrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtYXh1cHZxcG14dW9qeGRtd3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNDQ2OTIsImV4cCI6MjA2NjcyMDY5Mn0.jtAcgU4a6wbNjC0YB5l77XxAgof5V_XeeVoLshgRfgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});